apiVersion: v1
kind: ServiceAccount
metadata:
  name: garbage-collector
  annotations:
    {{- range $key, $value := .Values.primary_site.serviceAccountAnnotations.garbageCollector }}
      {{ $key }}: {{ $value }}
    {{- end }}
