apiVersion: v1
kind: ServiceAccount
metadata:
  name: inbox-listener
  annotations:
    {{- range $key, $value := .Values.primary_site.serviceAccountAnnotations.inboxListener }}
      {{ $key }}: {{ $value }}
    {{- end }}
