apiVersion: v1
kind: ServiceAccount
metadata:
  name: stream-service
  annotations:
    {{- range $key, $value := .Values.primary_site.serviceAccountAnnotations.streamService }}
      {{ $key }}: {{ $value }}
    {{- end }}
