{{- $indexingStrategy := include "primary-site.indexingStrategy" . }}
{{- if eq $indexingStrategy "split-files" }}
{{- with .Values.garbageCollector.deployment.serviceAccount }}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garbage-collector
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
