{{- $indexingStrategy := include "primary-site.indexingStrategy" . }}
{{- if eq $indexingStrategy "index-in-place" }}
{{- with .Values.indexer.deployment.serviceAccount }}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexer
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
