{{- $values :=  mustMerge (.Values.queryEngine | default dict) (.Values.streamService | default dict) }}
{{- with $values.deployment.serviceAccount }}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: query-engine
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
{{- end }}
