apiVersion: v1
kind: Service
metadata:
  name: edge-controller
  labels:
    app: foxglove-edge-site
    {{- range $key, $value := .Values.edgeController.serviceLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: foxglove-edge-site
  ports:
    - name: controller
      protocol: TCP
      port: 8888
      targetPort: 9099
    - name: metrics
      protocol: TCP
      port: 6001
      targetPort: 6001
