apiVersion: v1
kind: Service
metadata:
  name: edge-controller
spec:
  selector:
    app: foxglove-edge-site
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 9099
    - protocol: TCP
      port: 6002
      targetPort: 6002
