name: CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: lint
        run: helm lint charts/*

  test_query_optimized_primary_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start minio
        run: docker compose up minio -d
        working-directory: tests
      - name: Create minio buckets
        run: docker compose up createbuckets
        working-directory: tests
      - uses: medyagh/setup-minikube@v0.0.20
      - name: Test primary site chart install
        timeout-minutes: 5
        env:
          FOXGLOVE_API_URL: ${{ vars.TEST_PRIMARY_SITE_API_URL }}
          FOXGLOVE_SITE_TOKEN: ${{ secrets.TEST_PRIMARY_SITE_TOKEN }}
        run: ./tests/test-query-optimized-primary-site-chart.sh ./charts/primary-site
  test_index_in_place_primary_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start minio
        run: docker compose up minio -d
        working-directory: tests
      - name: Create minio buckets
        run: docker compose up createbuckets
        working-directory: tests
      - uses: medyagh/setup-minikube@v0.0.20
      - name: Test primary site chart install
        timeout-minutes: 5
        env:
          FOXGLOVE_API_URL: ${{ vars.TEST_PRIMARY_SITE_API_URL }}
          FOXGLOVE_SITE_TOKEN: ${{ secrets.TEST_INDEX_IN_PLACE_PRIMARY_SITE_TOKEN }}
        run: ./tests/test-index-in-place-primary-site-chart.sh ./charts/primary-site

  test_remote_data_loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start minio
        run: docker compose up minio -d
        working-directory: tests
      - name: Create minio buckets
        run: docker compose up createbuckets
        working-directory: tests
      - uses: medyagh/setup-minikube@v0.0.20
        with:
          addons: metrics-server
      - name: Test remote data loader chart install
        timeout-minutes: 5
        run: ./tests/test-remote-data-loader-chart.sh ./charts/remote-data-loader
