{{- $values :=  mustMerge (.Values.queryEngine | default dict) (.Values.streamService | default dict) }}
apiVersion: v1
kind: Service
metadata:
  name: queryEngine
  annotations:
    {{- range $key, $value := $values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 6001
      protocol: TCP
      targetPort: 6001
  selector:
    app: query-engine
