apiVersion: v1
kind: Service
metadata:
  name: site-controller
  annotations:
    {{- range $key, $value := .Values.siteController.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 6001
      protocol: TCP
      targetPort: 6001
  selector:
    app: site-controller
